target: build execute clean

build:
	gcc -o bin1 ./project/src1.c
	gcc -o bin2 ./project/src2.c
	gcc -o bin3 ./project/src3.c
execute:
	./bin1
	./bin2
	./bin3

clean: 
	rm -f *.o
	rm -f bin1 bin2 bin3
